<a href="https://colab.research.google.com/github/asqarbek21/week1/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [ ]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor(42)
scalar

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(42)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [ ]:
# TODO: Create a vector tensor
vector = torch.tensor([1, 2, 3, 4])
vector
# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([1, 2, 3, 4])
Number of dimensions: 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [ ]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
matrix

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [ ]:
# TODO: Create a 3D tensor
tensor_3d = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor_3d

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
Number of dimensions: 3
Shape: torch.Size([1, 3, 3])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [ ]:
# TODO: Create random tensor
random_tensor = torch.rand(size=(4, 4))
random_tensor, random_tensor.dtype

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.3156, 0.2727, 0.3142, 0.1867],
        [0.0168, 0.2106, 0.3977, 0.8760],
        [0.5715, 0.5729, 0.4187, 0.4409],
        [0.6496, 0.8112, 0.3829, 0.0907]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [ ]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(size=(3, 224, 224))
image_tensor.shape, image_tensor.ndim

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [ ]:
# TODO: Create zeros tensor
zeros = torch.zeros(size=(5, 5))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 torch.float32)

### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [ ]:
random_tensor = torch.rand(3, 3)
# TODO: Create ones like
ones = torch.ones(size=(3, 3))
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [ ]:
# TODO: Create range tensor
range_tensor = torch.range(0, 20)
zero_to_twenty = torch.arange(start=0, end=20, step=2)
zero_to_twenty


/tmp/ipython-input-1687964405.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range_tensor = torch.range(0, 20)


tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [ ]:
# TODO: float16 tensor
float16_tensor = float_16_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

# TODO: int64 tensor
int64_tensor = int64_tensor_ = torch.tensor([1.0, 2.0, 3.0],
                               dtype=torch.float64) # torch.half would also work

float_16_tensor.dtype

torch.float16

### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [ ]:
# TODO: Change dtype
float32_tensor =

## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [ ]:
# TODO: Create tensor and print info
some_tensor = torch.rand(2, 3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[[0.3063, 0.9103, 0.2779, 0.5628],
         [0.8088, 0.7910, 0.5471, 0.3677],
         [0.7820, 0.5921, 0.5023, 0.8879]],

        [[0.3972, 0.0449, 0.7591, 0.6816],
         [0.5248, 0.1793, 0.6128, 0.9383],
         [0.9194, 0.4780, 0.7459, 0.2720]]])
Shape of tensor: torch.Size([2, 3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [ ]:
tensor = torch.tensor([10, 20, 30])

# TODO: Add 5
tensor + 5

# TODO: Subtract 10
tensor = tensor - 10

# TODO: Multiply by 2
tensor * 2

# TODO: Divide by 10
tensor / 10


tensor([0., 1., 2.])

### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [ ]:
import torch

# Create random tensors
A = torch.rand(2, 3)
B = torch.rand(3, 2)

# Perform matrix multiplication
C = torch.matmul(A, B)

print("Tensor A (2x3):")
print(A)

print("\nTensor B (3x2):")
print(B)

print("\nResult of A x B (2x2):")
print(C)


Tensor A (2x3):
tensor([[0.6428, 0.8540, 0.8494],
        [0.2653, 0.6340, 0.7958]])

Tensor B (3x2):
tensor([[0.4022, 0.8721],
        [0.6754, 0.6592],
        [0.4839, 0.3114]])

Result of A x B (2x2):
tensor([[1.2464, 1.3881],
        [0.9200, 0.8971]])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [ ]:
x = torch.arange(0, 100)

print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")
# TODO: Min

# TODO: Max

# TODO: Mean (note: may need to cast to float)

# TODO: Sum

Minimum: 0
Maximum: 99
Mean: 49.5
Sum: 4950


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [ ]:
# TODO: Argmin

tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

# TODO: Argmax

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [ ]:
reshape_tensor = torch.arange(10)
import torch
x = torch.arange(2., 5.)
x, x.shape

(tensor([2., 3., 4.]), torch.Size([3]))

### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [ ]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
# TODO: Stack vertically (dim=0)
tensor1 = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
tensor1

# TODO: Stack horizontally (dim=1)
tensor2 = torch.stack([x, x, x, x], dim=1)
tensor2



tensor([[2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.]])

### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [ ]:
x_squeezed = torch.rand(1, 3, 1)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[[0.2721],
         [0.7803],
         [0.7813]]])
Previous shape: torch.Size([1, 3, 1])

New tensor: tensor([[[[0.2721],
          [0.7803],
          [0.7813]]]])
New shape: torch.Size([1, 1, 3, 1])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [ ]:
x_original = torch.rand(size=(3, 100, 100))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([3, 100, 100])
New shape: torch.Size([100, 3, 100])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [ ]:
import torch

# Create the tensor
x = torch.tensor([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]])

print(x.shape)  # torch.Size([1, 3, 3])
value = x[0, 1, 1]
print(value)  # tensor(5)
second_row = x[0, 1]
print(second_row)  # tensor([4, 5, 6])


torch.Size([1, 3, 3])
tensor(5)
tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [ ]:
import numpy as np
import torch

arr = np.array([1, 2, 3, 4])
tensor = torch.from_numpy(arr)

print(tensor)


tensor([1, 2, 3, 4])


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [ ]:
import torch

tensor = torch.tensor([5, 6, 7, 8])
arr = tensor.numpy()

print(arr)


[5 6 7 8]


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [ ]:
# TODO: Set seed
torch.manual_seed(77)
rand1 = torch.rand(2,2)

# TODO: Reset seed for second tensor

rand2 = torch.rand(2,2)

# Check equality
print(rand1 == rand2)

tensor([[False, False],
        [False, False]])


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [ ]:
import torch
torch.cuda.is_available()

False

### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [ ]:
import torch

# Create tensor
x = torch.tensor([1, 2, 3, 4])

# Move to GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x = x.to(device)

# Move back to CPU and convert to NumPy
x_cpu = x.to("cpu")
arr = x_cpu.numpy()

print(arr)


[1 2 3 4]
